project:
  type: website

website:
  title: "web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu:
          - href: examples/quarto-bash.qmd
            text: Bash Example
          - href: examples/quarto-python.qmd
            text: Python Example
          - href: examples/quarto-r.qmd
            text: R Example
          - href: examples/quarto.qmd
            text: Quarto Example
    tools:
      - icon: book
        href: https://benson1231.gitbook.io/benson1231-docs
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/benson1231/quarto-training
          - text: Report a Bug
            href:  https://github.com/benson1231/quarto-training/issues

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



